import type {
  AppSnapshot,
  ConnectPost,
  ConnectTab,
  FeaturedArtisan,
  HeritageCard,
  HomeActivity,
  JambaarMission,
  LiveProgramItem,
  LiveTab,
  MarketProduct,
  MarketTab,
  MedalRow,
  NavItem,
  QuickAction,
} from './models';

export const shellNavItems: NavItem[] = [
  { id: 'home', label: 'Accueil', route: '/home', icon: 'home', tone: 'orange', exact: true },
  { id: 'connect', label: 'Connect', route: '/connect', icon: 'users', tone: 'navy', exact: true },
  { id: 'live', label: 'JOJ Live', route: '/live', icon: 'radio', tone: 'red', exact: true },
  { id: 'jambaar', label: 'Jambaar', route: '/jambaar', icon: 'award', tone: 'green', exact: true },
  { id: 'market', label: 'Marché', route: '/marketplace', icon: 'shopping-bag', tone: 'gold', exact: true },
];

export const homeQuickActions: QuickAction[] = [
  {
    id: 'connect',
    label: 'Connect',
    subtitle: 'Réseau social multilingue',
    route: '/connect',
    icon: 'users',
    tone: 'orange',
  },
  {
    id: 'live',
    label: 'JOJ Live',
    subtitle: 'Programme et médailles',
    route: '/live',
    icon: 'radio',
    tone: 'navy',
  },
  {
    id: 'jambaar',
    label: 'Jambaar',
    subtitle: 'Missions et points',
    route: '/jambaar',
    icon: 'award',
    tone: 'green',
  },
  {
    id: 'market',
    label: 'Marche',
    subtitle: 'Artisans certifiés',
    route: '/marketplace',
    icon: 'shopping-bag',
    tone: 'gold',
  },
  {
    id: 'heritage',
    label: 'Heritage',
    subtitle: 'Mémoire des JOJ',
    route: '/heritage',
    icon: 'archive',
    tone: 'teal',
  },
];

export const homeActivitySeed: HomeActivity[] = [
  {
    id: 'activity-live',
    icon: 'trophy',
    title: "Tir à l'arc - Finale en LIVE",
    subtitle: 'Diamniadio · Jamal Diallo · Sénégal en lice',
    value: 'LIVE',
    tone: 'orange',
    action: 'navigate',
    route: '/live',
  },
  {
    id: 'activity-like',
    icon: 'heart',
    title: 'Likes sur votre post JOJ',
    subtitle: 'Communauté · il y a 2h',
    value: '+142 pts',
    tone: 'red',
    action: 'toast',
    message: '+710 FCFA',
  },
  {
    id: 'activity-mission',
    icon: 'award',
    title: 'Mission Fan Zone completee',
    subtitle: 'Jambaar Hub · il y a 5h',
    value: '+500 pts',
    tone: 'green',
    action: 'navigate',
    route: '/jambaar',
    message: '+2 500 FCFA',
  },
  {
    id: 'activity-market',
    icon: 'shopping-bag',
    title: 'Achat marche certifie',
    subtitle: 'Marche · il y a 8h',
    value: '+320 pts',
    tone: 'gold',
    action: 'navigate',
    route: '/marketplace',
    message: '+1 600 FCFA',
  },
  {
    id: 'activity-withdraw',
    icon: 'banknote',
    title: 'Retrait Orange Money',
    subtitle: 'Wallet · maintenant',
    value: '1 235 FCFA',
    tone: 'navy',
    action: 'toast',
    message: 'Voir l’historique Orange Money',
  },
];

export const connectTabs: ConnectTab[] = [
  { id: 'all', label: 'Tous', icon: 'globe' },
  { id: 'wolof', label: 'Wolof', icon: 'message-circle' },
  { id: 'pulaar', label: 'Pulaar', icon: 'users' },
  { id: 'diola', label: 'Diola', icon: 'compass' },
  { id: 'joj', label: '#JOJ2026', icon: 'sparkles' },
];

export const connectPosts: ConnectPost[] = [
  {
    id: 'post-1',
    author: 'Aminata Fall',
    handle: '@aminata.fall',
    city: 'Dakar',
    language: 'Wolof',
    accent: '#FF6B00',
    time: '2 h',
    text:
      'Dafa baax lool ! JOJ yi daan fi. Senegaal doole bi dafa am, et toute la ville vit au rythme du stade.',
    tags: ['#JOJ2026', '#Wolof', '#Dakar'],
    likes: 142,
    comments: 23,
    shares: 18,
    rewards: 4,
    boosted: true,
    boostLabel: 'x2',
    mediaLabel: 'Capsule terrain',
    mediaTone: 'surface',
  },
  {
    id: 'post-2',
    author: 'Ibrahima Badji',
    handle: '@ibra.badji',
    city: 'Ziguinchor',
    language: 'Diola',
    accent: '#00A859',
    time: '4 h',
    text:
      'Notre fils Moussa est qualifié pour la finale. Toute la famille de Ziguinchor suit les JOJ, de la maison jusqu’aux fan zones.',
    tags: ['#JOJ2026', '#Diola', '#Famille'],
    likes: 89,
    comments: 14,
    shares: 11,
    rewards: 2,
    boosted: true,
    boostLabel: 'x2',
    mediaLabel: 'Message diaspora',
    mediaTone: 'surface',
  },
  {
    id: 'post-3',
    author: 'Rokhaya Sow',
    handle: '@rokhaya.sow',
    city: 'Paris',
    language: 'FR',
    accent: '#0891B2',
    time: '6 h',
    text:
      'Grâce à AfriStory JOJ je vis les Jeux avec ma famille à Dakar en temps réel. On partage, on soutient, on reste connectés.',
    tags: ['#Diaspora', '#JOJ2026', '#Famille'],
    likes: 234,
    comments: 41,
    shares: 26,
    rewards: 7,
    boosted: false,
    mediaLabel: 'Connexion diaspora',
    mediaTone: 'surface',
  },
];

export const liveTabs: LiveTab[] = [
  { id: 'program', label: 'Programme', icon: 'calendar' },
  { id: 'medals', label: 'Médailles', icon: 'medal' },
  { id: 'senegal', label: 'Sénégal', icon: 'flag' },
];

export const liveProgram: LiveProgramItem[] = [
  {
    id: 'event-1',
    time: '10:00',
    icon: 'trophy',
    title: 'Tir à l’arc — Finale',
    venue: 'Diamniadio · Jamal Diallo',
    badge: '● LIVE',
    badgeTone: 'red',
    toast: 'Tir à l’arc — Jamal Diallo EN FINALE !',
  },
  {
    id: 'event-2',
    time: '11:30',
    icon: 'award',
    title: 'Judo — Demi-finale',
    venue: 'Dakar Arena · Fatou Cissé',
    badge: 'SN',
    badgeTone: 'green',
    toast: 'Judo — Fatou Cissé en demi-finale !',
  },
  {
    id: 'event-3',
    time: '14:00',
    icon: 'sparkles',
    title: 'Breaking — Qualifications',
    venue: 'Corniche · 3 athlètes sénégalais',
    badge: 'Qualif.',
    badgeTone: 'orange',
    toast: 'Breaking — 3 athlètes sénégalais qualifiés !',
  },
  {
    id: 'event-4',
    time: '15:30',
    icon: 'play',
    title: 'Skateboard — Finale',
    venue: 'Saly · Aminata Samb',
    badge: 'Finale',
    badgeTone: 'purple',
    toast: 'Skateboard — Aminata Samb en finale !',
  },
];

export const medalRows: MedalRow[] = [
  {
    rank: 1,
    country: 'USA',
    code: 'US',
    flag: 'US',
    gold: 18,
    silver: 14,
    bronze: 13,
    accent: '#E11D48',
    toast: 'USA — 45 médailles',
  },
  {
    rank: 2,
    country: 'Chine',
    code: 'CN',
    flag: 'CN',
    gold: 15,
    silver: 12,
    bronze: 14,
    accent: '#0F766E',
    toast: 'Chine — 41 médailles',
  },
  {
    rank: 5,
    country: 'Kenya',
    code: 'KE',
    flag: 'KE',
    gold: 9,
    silver: 8,
    bronze: 11,
    accent: '#2563EB',
    toast: 'Kenya — 28 médailles',
  },
  {
    rank: 8,
    country: 'Sénégal',
    code: 'SN',
    flag: 'SN',
    gold: 7,
    silver: 4,
    bronze: 9,
    accent: '#FF6B00',
    highlighted: true,
    toast: 'ALLEZ SÉNÉGAL ! 20 médailles !',
  },
  {
    rank: 12,
    country: 'Maroc',
    code: 'MA',
    flag: 'MA',
    gold: 5,
    silver: 6,
    bronze: 5,
    accent: '#7C3AED',
    toast: 'Maroc — 16 médailles',
  },
  {
    rank: 15,
    country: 'Nigeria',
    code: 'NG',
    flag: 'NG',
    gold: 4,
    silver: 5,
    bronze: 5,
    accent: '#F97316',
    toast: 'Nigeria — 14 médailles',
  },
];

export const jambaarMissions: JambaarMission[] = [
  {
    id: 'm1',
    icon: 'users',
    title: 'Organiser une Fan Zone',
    description: 'Réunir 20+ personnes dans votre quartier',
    points: 500,
    fcfa: 2500,
    peopleTouched: 20,
    accent: '#FF6B00',
    done: false,
    toast: '+500 pts — Fan Zone organisée !',
  },
  {
    id: 'm2',
    icon: 'video',
    title: 'Créer une capsule vidéo',
    description: '90 sec en wolof ou pulaar',
    points: 200,
    fcfa: 1000,
    peopleTouched: 15,
    accent: '#0891B2',
    done: false,
    toast: '+200 pts — Capsule vidéo publiée !',
  },
  {
    id: 'm3',
    icon: 'megaphone',
    title: 'Sensibiliser 50 personnes',
    description: 'Partager les capsules JOJ',
    points: 300,
    fcfa: 1500,
    peopleTouched: 50,
    accent: '#00A859',
    done: false,
    toast: '+300 pts — 50 personnes sensibilisées !',
  },
  {
    id: 'm4',
    icon: 'star',
    title: 'Mission spéciale — Cérémonie',
    description: "Couvrir la cérémonie d'ouverture",
    points: 1000,
    fcfa: 5000,
    peopleTouched: 100,
    accent: '#FFC800',
    done: false,
    toast: '+1000 pts — Mission spéciale validée !',
  },
];

export const marketTabs: MarketTab[] = [
  { id: 'all', label: 'Tout' },
  { id: 'bijoux', label: 'Bijoux' },
  { id: 'tissus', label: 'Tissus' },
  { id: 'sculpture', label: 'Sculpture' },
  { id: 'epices', label: 'Épices' },
];

export const featuredArtisan: FeaturedArtisan = {
  name: 'Rokhaya Sow',
  role: 'Tissus wax · bijoux · Médina Dakar',
  location: 'Médina Dakar',
  sales: 47,
  rating: 4.9,
  badge: 'Artisane certifiée AfriStory',
  accent: '#0A1128',
  icon: 'sparkles',
  toast: 'Rokhaya Sow — Artisane certifiée | 47 ventes | 4.9/5',
};

export const marketProducts: MarketProduct[] = [
  {
    id: 'p1',
    icon: 'badge-check',
    name: 'Collier Wax Wolof',
    category: 'Bijou',
    price: 8500,
    tone: 'gold',
    accent: '#FFC800',
    certified: true,
    paymentNote: 'Paiement Orange Money : 8 500 FCFA',
    toast: 'Collier Wax Wolof — Paiement Orange Money : 8 500 FCFA',
  },
  {
    id: 'p2',
    icon: 'scarf',
    name: 'Tissu Bazin Brodé',
    category: 'Tissus',
    price: 22000,
    tone: 'orange',
    accent: '#FF6B00',
    certified: true,
    paymentNote: 'Paiement Orange Money : 22 000 FCFA',
    toast: 'Tissu Bazin Brodé — Paiement Orange Money : 22 000 FCFA',
  },
  {
    id: 'p3',
    icon: 'shield',
    name: 'Masque Diola',
    category: 'Sculpture',
    price: 15000,
    tone: 'green',
    accent: '#00A859',
    certified: true,
    paymentNote: 'Paiement Orange Money : 15 000 FCFA',
    toast: 'Masque Diola — Paiement Orange Money : 15 000 FCFA',
  },
  {
    id: 'p4',
    icon: 'flame',
    name: 'Épices Yaakar',
    category: 'Épices',
    price: 6500,
    tone: 'purple',
    accent: '#7C3AED',
    certified: false,
    paymentNote: 'Paiement en cours...',
    toast: 'Épices Yaakar — Paiement en cours...',
  },
  {
    id: 'p5',
    icon: 'music',
    name: 'Djembé Miniature',
    category: 'Artisanat',
    price: 35000,
    tone: 'teal',
    accent: '#0891B2',
    certified: false,
    paymentNote: 'Livraison disponible partout',
    toast: 'Djembé Miniature — Livraison disponible partout',
  },
  {
    id: 'p6',
    icon: 'crown',
    name: 'Boubou Bazin Royal',
    category: 'Tissus',
    price: 48000,
    tone: 'navy',
    accent: '#0A1128',
    certified: false,
    paymentNote: 'Carte internationale disponible',
    toast: 'Boubou Bazin Royal — Paiement par carte internationale disponible',
  },
];

export const heritageCards: HeritageCard[] = [
  {
    id: 'h1',
    icon: 'flame',
    badge: 'Jour 1',
    title: "Cérémonie d'ouverture — JOJ Dakar 2026",
    description:
      "L'Afrique entre dans l'histoire olympique. Premier événement olympique sur le sol africain en 128 ans d'histoire olympique.",
    tags: ['Historique', 'Dakar', '#JOJ2026'],
    tone: 'orange',
    toast: 'Premier JO africain — 31 Octobre 2026 !',
  },
  {
    id: 'h2',
    icon: 'medal',
    badge: 'Jour 3',
    title: 'Jamal Diallo — 1ère médaille d’or',
    description:
      "17 ans. Tir à l'arc. De Rufisque à l'or olympique. Une histoire préservée pour les 15 prochaines années.",
    tags: ['Or', 'Tir à l’arc', 'Sénégal'],
    tone: 'navy',
    toast: 'Jamal Diallo — 1ère médaille d’or sénégalaise !',
  },
  {
    id: 'h3',
    icon: 'sparkles',
    badge: 'Jour 5',
    title: "Breaking — L'Afrique danse au monde",
    description:
      '3 athlètes sénégalais en finale de breaking. La culture urbaine africaine au centre du monde.',
    tags: ['Breaking', 'Culture', 'Jeunesse'],
    tone: 'green',
    toast: "Breaking — L'Afrique danse au monde !",
  },
  {
    id: 'h4',
    icon: 'archive',
    badge: 'Forever',
    title: 'Archive AfriStory JOJ — Ouverte pour toujours',
    description:
      'Tous les moments, histoires et performances des JOJ 2026 préservés pour les générations futures.',
    tags: ['Éducation', 'Patrimoine', '15 ans'],
    tone: 'purple',
    toast: 'Archive disponible pour les générations futures !',
  },
];

function cloneData<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

export function createInitialSnapshot(): AppSnapshot {
  return {
    points: 247,
    missionsDone: 12,
    peopleTouched: 340,
    connectPosts: cloneData(connectPosts),
    jambaarMissions: cloneData(jambaarMissions),
    activityFeed: cloneData(homeActivitySeed),
  };
}
